env:
  global:
    - CC_TEST_REPORTER_ID=2524769fd0a5dfa11ad82bf315107eb334ce5fca7e446cf0190a8ea4cb3363b7
language: java
sudo: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cd my-app/
script: mvn test
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
